language: python

python:
 - "3.4"

notifications:
  email: false

services:
  - redis-server

before_install:
  - "export TERM=dumb"

install:
 - cd ..
 - git clone --depth 1 https://github.com/Qabel/qabel.git
 - cd qabel
 - git submodule init
 - git submodule update --depth 1
 - rm -rf qabel-core
 - mv ../qabel-core ./
 - pip install -r qabel-drop/requirements.txt
 - pip install -r qabel-accounting/requirements.txt

cache:
 apt: true
 pip: true
 directories:
  - $HOME/.gradle/caches

sudo: false

script:
 - ./gradlew check
